services:
  telegram-server:
    build: 
      context: .
      dockerfile: telegram-bot-server/Dockerfile
      args:
        - BUILD_JOBS=${BUILD_JOBS}
    ports: ["${TELEGRAM_HTTP_PORT}:${TELEGRAM_HTTP_PORT}"]
    environment:
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - HTTP_PORT=${TELEGRAM_HTTP_PORT}
  bot-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - BASE_URL=${BASE_URL}:${TELEGRAM_HTTP_PORT}
      - YT_DLP_PATH=${YT_DLP_PATH}
      - COOKIES_PATH=${COOKIES_PATH}
      - JS_RUNTIME=${JS_RUNTIME}
